using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GridViewApplication.Dto.RestLogin
{
    public class rest_response_login
    {
        /// <example>eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoWTZoQXBSQ2NMM0c2SkN2dUF4OW5vUE9mWTBqQ2lrZWVwV2hoRlZwOTYwIn0.eyJleHAiOjE2OTU3MDI3NDksImlhdCI6MTY5NTY5OTE0OSwianRpIjoiNTJjMDEzZmUtODQxMS00N2Q2LWFlZjUtZDI1OTUxOGI5ODYzIiwiaXNzIjoiaHR0cHM6Ly9zc28tYXBpZ3ctaW50LmR0aS5jby5pZC9hdXRoL3JlYWxtcy8zc2NhbGUtZGV2IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImRhNjBiMzJiLTk4ODctNDUzZS04YTcxLTNiNDM1ODc5MDJiMiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImQ1ZWIxMmZhIiwic2Vzc2lvbl9zdGF0ZSI6IjEwMzkzM2EyLWFhZmQtNDJjNy04N2RlLTJmOWE2Mzc5YmNjZSIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtM3NjYWxlLWRldiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjEwMzkzM2EyLWFhZmQtNDJjNy04N2RlLTJmOWE2Mzc5YmNjZSIsImNsaWVudEhvc3QiOiIxMC4yNy40LjEyIiwiY2xpZW50SWQiOiJkNWViMTJmYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LWQ1ZWIxMmZhIiwiY2xpZW50QWRkcmVzcyI6IjEwLjI3LjQuMTIifQ.aOAYThflbsL_ptIyfqr9AlWqqLx_Tuu5C7QUzXvRoBaWmwY79Ydw_RSyDGeFSrmc6x7iHjZ-Pz_jpl-idoqiwexFdnolfs-Ng1wZj2iHMBehXm7PybzshhN5I332ZjCquCpvbR2K3suLktBBXCaKeejM8nYEPb6wiOMNJG-AqKrHAtQkKdjAmQW5Hh2Wwxd-CxDSBfn0MNiwfxMz2XZHp27oArbldcWe6WkQZhTczZZKvBLq9J-oXcjWwPQ0hi5qC21gz-t_RrnUgazbxR4khjNaIxzBGdAVEJYO83yw0kT7n3YcnKBb-puE0Y7FDTXMOnba2TPBCVkUgc3EmvcCCg</example>
        public string jwtToken { get; set; }        
    }    
}